### ISSUE TITLE
Minikube install chaincode

### ISSUE THREAD

**Issue by MaxRos1234** [vanitas92/fabric-external-chaincodes#3] opened 2020-05-11 10:47 UTC
Hi Pau.

I am using minikube and when I install the chaincode from the "CLI" container using "peer lifecycle chaincode install marbles-org1.tgz" I get:

Error: chaincode install failed with status: 500 - failed to invoke backing implementation of 'InstallChaincode': could not build chaincode: docker build failed: docker image inspection failed: cannot connect to Docker endpoint
can you help?

**Comment by vanitas92** [comment] 2020-05-11 11:24
Hi @MaxRos1234 ,

I cannot support you on the environment on minikube, so if there is something wrong with kubernetes environment i would fail to detect.

For the error you are mentioning, other people have came with the same problem and i would suggest you make sure that these 3 scripts have execution permissions in the buildpack/bin folder. The scripts are executed in the peer pod as root so changing to 744 permission should be enough. Failing to do so will cause the externalbuilder to fail its execution.

If that does not work either, make sure you had packaged correctly the chaincode format as explained in the tutorial, otherwise the external builder would not be able to detect it and install it as external chaincode. Check the logs of the peer (`kubectl logs peer_pod_name -n hyperledger | grep external`) and see what message outputs the external builder after executing the install command.

**Comment by MaxRos1234** [comment] 2020-05-11 14:43
Thanks, problem solved

**Comment by vanitas92** [comment] 2020-05-11 14:50
Closing the issue since the problem is solved.

**Closed as completed by vanitas92** 2020-05-11 14:50 UTC
